name: Publish snapshot

on:
  pull_request:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Create & Publish Snapshot
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run snapshot:version
          publish: npm run snapshot:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
